[build]
  publish = "public"
  command = "yarn build"
[context.branch-deploy]
  ignore = "bash ./netlify-build-ignore.sh"
[build.environment]
  NODE_VERSION = "14.20.1" # minimum version required by Gatsby v4
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_OPTIONS = "--max-old-space-size=8192"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
     Referrer-Policy = "strict-origin-when-cross-origin"
[[headers]]     
  for = "/fonts/*"
    [headers.values]
     Access-Control-Allow-Origin = "*"
