backend:
  name: github
  branch: main
  repo: fntechgit/fnEvent
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "configurations"
    label: "Configurations"
    editor:
      preview: false
    files:
      - file: "src/content/settings.json"
        label: "General Settings"
        name: "generalSettings"
        fields:
          - {label: "Favicons", name: favicons, widget: object, fields: [
              {label: "Favicon 180x180", name: favicon180, widget: image},
              {label: "Favicon 32x32", name: favicon32, widget: image},
              {label: "Favicon 16x16", name: favicon16, widget: image}
            ]}
          - {label: "Widgets", name: widgets, widget: object, fields: [
              {label: "Chat", name: chat, widget: object, fields: [
                {label: "Show QA", name: showQA, widget: boolean, required: false, default: false},
                {label: "Show Help", name: showHelp, widget: boolean, required: false, default: false},
                {label: "Default Filter Criteria", name: defaultScope, widget: select, required: false, default: 'page', options: [
                  {label: "In this Room", value: "page" },
                  {label: "All Attendees", value: "show" }
                ]}
              ]}
            ]}
      - file: "src/content/ads.json"
        label: "Advertisement"
        name: "ads"
        fields:
          - {label: "Ads", name: "ads", widget: list, fields: [
              {label: "Page", name: "section", widget: string},                          
              {label: "Ads", name: "columnAds", widget: list, required: false, fields: [
                {label: "Image", name: "image", widget: object, required: false, fields: [
                  {label: "File", name: "file", widget: image, required: false, default: '' },
                  {label: "Alt", name: "alt", widget: string, required: false, default: '' },
                ]},
                {label: "Button", name: "button", widget: object, required: false, fields: [
                  {label: "Text", name: "text", widget: string, required: false},
                  {label: "Link", name: "link", widget: string, required: false}
                ]},
                {label: "Column", name: "column", widget: select, options: [
                  {label: "Left", value: "left" },
                  {label: "Center", value: "center" },
                  {label: "Right", value: "right" },
                ]},
                {label: "Specific Event?", name: "id", widget: string, required: false, default: 0}
              ]},
            ]}
      - file: "src/content/sponsors-tiers.json"
        label: "Sponsors Tiers"
        name: "sponsorsTiers"
        fields:          
          - {label: "Expo Hall Header Image", name: "imageHeader", widget: object, required: false, fields: [{label: "File", name: "file", widget: image, default: '', required: false},{label: "Alt", name: "alt", widget: string, required: false}]}
          - {label: "Lobby Button", name: lobbyButton, widget: object, fields: [
              {label: "Text", name: "text", widget: string, required: false, default: ''},
              {label: "Link", name: "link", widget: string, required: false, default: ''}
            ]}
      - file: "src/content/navbar.json"
        label: "Navbar"
        name: "navbar"
        fields:
          - {label: "Navbar", name: "items", widget: list, fields: [
              {label: "Title", name: "title", widget: string},
              {label: "Link", name: "link", widget: string},
              {label: "Display?", name: "display", widget: boolean, required: false},
              {label: "Requires Auth?", name: "requiresAuth", widget: boolean, required: false, default: false},
              {label: "Show only at Show Time?", name: "showOnlyAtShowTime", widget: boolean, required: false, default: false},
              {label: "Show only on page", name: "pageRestriction", widget: select, multiple: true, default: ["ANY"], options: ["ANY", "MARKETING", "LOBBY", "ACTIVITY", "SHOW", "CUSTOM_PAGE"]},
            ]}
      - file: "src/content/footer.json"
        label: "Footer"
        name: "footer"
        fields:
          - {label: "Columns", name: "columns", widget: list, fields: [
              {label: "Title", name: "title", widget: string},
              {label: "Display", name: "display", widget: boolean, required: false},
              {label: "Items", name: "items", widget: list, fields: [
                {label: "Title", name: "title", widget: string},
                {label: "Link", name: "link", widget: string},         
              ]}
            ]}
          - {label: "Logo", name: "logo", widget: object, fields: [
              {label: "Display", name: "display", widget: boolean, required: false},
            ]}
          - {label: "Social", name: "social", widget: object, fields: [
              {label: "Title", name: "title", widget: string},
              {label: "Display", name: "display", widget: boolean, required: false},
              {label: "Networks", name: "networks", widget: list, fields: [
                {label: "Icon", name: "icon", widget: string},
                {label: "Link", name: "link", widget: string},
                {label: "Display", name: "display", widget: boolean, required: false},
              ]}
            ]}
          - {label: "Legal", name: "legal", widget: list, fields: [
              {label: "Title", name: "title", widget: string},
              {label: "Link", name: "link", widget: string},         
            ]}
      - file: "src/content/poster-pages.json"
        label: "Poster Pages"
        name: "poster-pages"
        fields:
          - {label: "Poster Pages", name: "posterPages", widget: list, fields: [
              {label: "Name", name: "name", widget: string, required: false},
              {label: "Track Group Id", name: "trackGroupId", widget: number },
              {label: "Title", name: "title", widget: string },
              {label: "Subtitle", name: "subtitle", widget: string },
              {label: "Background Image", name: "image", widget: image, required: false},
            ]}
  - name: "home"
    label: "Lobby Site"
    editor:
      preview: false
    files:
      - file: "src/content/home-settings.json"
        name: "homeSettings"
        label: "Lobby Settings"
        fields:
          - {label: "Center Column", name: "centerColumn", widget: object, fields: [
              {label: "Speakers", name: "speakers", widget: object, fields: [
                {label: "Show Today Speakers", name: "showTodaySpeakers", widget: boolean, required: false},
                {label: "Show Feature Speakers", name: "showFeatureSpeakers", widget: boolean, required: false}
              ]}
            ]}
          - {label: "Home Hero", name: homeHero, widget: object, fields: [
              {label: "Title", name: title, widget: string},
              {label: "Sub Title", name: subTitle, widget: string, required: false},
              {label: "Image", name: "image", widget: object, required: false, fields: [
                {label: "File", name: "file", widget: image, default: '', required: false},
                {label: "Alt", name: "alt", widget: string, required: false},
              ]},
              {label: "Copy", name: copy, widget: text, required: false}
            ]}
          - {label: "Featured Event - Live Event Widget", name: live_now_featured_event_id, widget: number, required: false, default: null}
  - name: "marketing"
    label: "Marketing Site"
    editor:
      preview: false
    files:
      - file: "src/content/marketing-site.json"
        name: "marketingSite"
        label: "Marketing Site"
        fields:
          - {label: "Hero Banner", name: "heroBanner", widget: "object", fields: [
              {label: "Title", name: "title", widget: string},
              {label: "Sub Title", name: "subTitle", widget: string, required: false},
              {label: "Date", name: "date", widget: string, required: false},
              {label: "Date Layout", name: "dateLayout", widget: boolean, required: false},
              {label: "Time", name: "time", widget: string, required: false},
              {label: "Buttons", name: "buttons", widget: object, fields: [
                {label: "Register Button", name: "registerButton", widget: object, fields: [
                  {label: "Text", name: "text", widget: string},
                  {label: "Display", name: "display", widget: boolean, required: false},
                ]},
                {label: "Login Button", name: "loginButton", widget: object, fields: [
                  {label: "Text", name: "text", widget: string},
                  {label: "Display", name: "display", widget: boolean, required: false},
                ]}                
              ]},
              {label: "Background Image", name: "background", widget: object, required: false, fields: [
                {label: "File", name: "file", widget: image, default: '', required: false},
                {label: "Alt", name: "alt", widget: string, required: false},
              ]},
              {label: "Images", name: "images", widget: list, fields: [
                { label: "File", name: "file", widget: image, default: '', required: false },
                { label: "Alt", name: "alt", widget: string, required: false },
              ]},
            ]}
          - {label: "Countdown", name: "countdown", widget: object, fields: [
              {label: "Should Display?", name: display, widget: boolean, required: false},
              {label: "Text", name: "text", widget: string}
            ]}
          - {label: "Widgets", name: "leftColumn", widget: object, fields: [
              {label: "Schedule", name: "schedule", widget: object, fields: [
                {label: "Display", name: "display", widget: boolean, required: false},
                {label: "Title", name: "title", widget: string, required: false},
              ]},
              {label: "Disqus", name: "disqus", widget: object, fields: [
                {label: "Display", name: "display", widget: boolean, required: false},
                {label: "Title", name: "title", widget: string, required: false},
              ]},
              {label: "Image", name: "image", widget: object, fields: [
                {label: "Display", name: "display", widget: boolean, required: false},
                {label: "Title", name: "title", widget: string, required: false},
                {label: "Image", name: "src", widget: image, required: false},
                {label: "Alt", name: "alt", widget: string, required: false},
              ]},
            ]}
          - {label: "Redirect to event", name: "eventRedirect", widget: number, required: false, hint: "User will be redirected to this event after login"}
          - {label: "Sponsors", name: "sponsors", widget: list, fields: [
              {label: "Name", name: title, widget: hidden},
              {label: "Size", name: size, widget: select, options: [
                {label: "Single", value: 1},
                {label: "Double", value: 2}
              ]},
              {label: "Images", name: "images", widget: list, fields: [
                {label: "Image", name: "image", widget: image, required: false},
                {label: "Link", name: "link", widget: string, required: false},
                {label: "Alt", name: "alt", widget: string, required: false},
              ]}
            ]}          
  - name: "virtualBooth"
    label: "Virtual Booth"
    files: 
      - file: "src/pages/virtual-booth.md"
        name: "virtualBoothPage"
        label: "Virtual Booth Page"      
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "virtual-booth-page"}
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - {label: Columns, name: columns, widget: object, fields: [
              {label: Left Column, name: leftColumn, widget: object, fields: [
                {label: Title, name: title, widget: string},
                {label: Content, name: content, widget: text},
                {label: Image, name: image, widget: image},
                {label: "Alt", name: "alt", widget: string, required: false},
              ]},
              {label: Right Column, name: rightColumn, widget: object, fields: [
                {label: Title, name: title, widget: string},
                {label: Content, name: content, widget: text},
                {label: Image, name: image, widget: image},
                {label: "Alt", name: "alt", widget: string, required: false},
              ]}
            ]}
          - {label: End Text, name: endText, widget: markdown}
          - {label: "Body", name: body, widget: markdown}
  - name: "pages"
    label: "Pages"
    folder: "src/pages/custom-pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "custom-page"}
      - {label: Title, name: title, widget: string}
      - {label: "User Requirement", name: userRequirement, widget: select, options: ["NONE", "LOGGED_IN", "HAS_TICKET"], default: "NONE"}
      - {label: "Body", name: body, widget: markdown}  
